spring:
  security:
    oauth2:
      client:
        registration:
          github:
            client-id: ${GITHUB_CLIENT_ID}
            client-secret: ${GITHUB_CLIENT_SECRET}
            client-name: Github user
            provider: github
            scope: user
            redirect-uri: http://localhost:8080/login/oauth2/code/github
          github-email:
            client-id: ${GITHUB_CLIENT_ID}
            client-secret: ${GITHUB_CLIENT_SECRET}
            client-name: Github email
            provider: github
            scope: user:email
            redirect-uri: http://localhost:8080/login/oauth2/code/github
          google:
            client-id: ${GOOGLE_CLIENT_ID}
            client-secret: ${GOOGLE_CLIENT_SECRET}
            client-name: Google user
            provider: google
            scope: email
            redirect-uri: http://localhost:8080/login/oauth2/code/google